import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./global.css";
import RootApp from "@/layouts/root-app";
import HolyLoader from "holy-loader";
import {ReactNode} from "react";
import {auth} from "@/auth";
import {SessionProvider} from "next-auth/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Peniato",
  description: "Generated by create next app",
};

export default async function  RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
    const session = await auth();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <HolyLoader color="#6f7686"/>
      <SessionProvider session={session}>
          <RootApp>
              {children}
          </RootApp>
      </SessionProvider>
      </body>
    </html>
  );
}
