import type { Metadata } from "next";
import "./globals.css";
import {auth} from "@/auth";
import {SessionProvider} from "next-auth/react";
import HolyLoader from "holy-loader";
import RootApp from "@/layouts/root-app";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const session = await auth();

    return (
    <html lang="en">
      <body>
      <HolyLoader color="#6f7686"/>
      <SessionProvider session={session}>
          <RootApp>
              {children}
          </RootApp>
      </SessionProvider>
      </body>
    </html>
  );
}
